import Link from 'next/link';

const features = [
  { title: 'AI Builder', desc: 'Describe your idea in plain language. The agent plans, writes files, fixes errors, and builds a working project.', icon: '🤖' },
  { title: 'Visual Builder', desc: 'Point, click, tweak. Visual edits sync with real code — never a fake canvas.', icon: '🎨' },
  { title: 'Full-stack Agent', desc: 'Read, write, edit, search, run commands, install packages — inside an isolated sandbox with safety confirmations.', icon: '⚙️' },
  { title: 'GitHub', desc: 'Connect GitHub, create repositories, commit, push, branch — from the workspace or by asking the agent.', icon: '🐙' },
  { title: 'Supabase', desc: 'Provision tables, auth, storage, and RLS policies. Migrations generated by the agent.', icon: '🗄️' },
  { title: 'Vercel Deploy', desc: 'One command from project to production URL. Preview deployments included.', icon: '▲' },
  { title: 'CLI & more', desc: 'Same agent engine powers web, CLI, VS Code, and desktop. One brain, many surfaces.', icon: '⌨️' },
  { title: 'Free-first AI', desc: 'Start with zero setup — no Ollama, no API keys. Bring your own model keys anytime for unlimited use.', icon: '✨' },
];
const faqs = [
  ['Do I need Ollama or any local AI?', 'No. Olze routes your requests through the Olze AI Gateway using free-tier providers server-side. Ollama is entirely optional for privacy-focused users.'],
  ['Is it really free?', 'Yes — free to start, no credit card. Free usage has fair-use limits (requests/month) because inference costs money. Add your own API key (BYO) to remove Olze-side limits.'],
  ['Can I export my code?', 'Always. Your projects are real files in a real repo structure. Connect GitHub and it is yours in seconds.'],
  ['What can the agent do?', 'Inspect your project, plan changes, create/edit files, run builds and tests, fix errors, wire up Supabase, push to GitHub, and deploy to Vercel — with confirmations on dangerous actions.'],
];

export default function Landing() {
  return (
    <main>
      {/* Nav */}
      <header className="sticky top-0 z-40 border-b border-slate-800/60 bg-[#0b0f1a]/80 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2 font-bold text-white">
            <img src="/olze-icon.svg" alt="Olze" className="h-7 w-7" /> Olze
          </Link>
          <nav className="hidden items-center gap-8 text-sm text-slate-400 md:flex">
            <a href="#features" className="hover:text-white">Features</a>
            <a href="#how" className="hover:text-white">How it works</a>
            <a href="#faq" className="hover:text-white">FAQ</a>
          </nav>
          <div className="flex items-center gap-3">
            <Link href="/login" className="text-sm text-slate-300 hover:text-white">Sign in</Link>
            <Link href="/signup" className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white hover:bg-brand-500">Start free</Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(60%_50%_at_50%_0%,rgba(99,102,241,0.25),transparent)]" />
        <div className="mx-auto max-w-4xl px-6 pb-20 pt-24 text-center">
          <p className="mb-4 inline-flex items-center gap-2 rounded-full border border-slate-700 px-4 py-1 text-xs text-slate-400">
            ✦ Free-first AI development platform
          </p>
          <h1 className="bg-gradient-to-br from-white via-slate-200 to-slate-400 bg-clip-text text-5xl font-extrabold tracking-tight text-transparent md:text-7xl">
            Build anything with AI.
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg text-slate-400">
            Design, code, connect your backend, and deploy — all from one place.
            Describe your idea and watch a real full-stack project take shape.
          </p>
          <div className="mt-10 flex flex-wrap items-center justify-center gap-4">
            <Link href="/signup" className="btn-primary">Start Building Free →</Link>
            <a href="https://github.com/olze/olze" className="btn-ghost">☆ View GitHub</a>
          </div>
          <p className="mt-6 text-sm text-slate-500">
            No Ollama required · No credit card required · Fair-use free tier
          </p>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="mx-auto max-w-6xl px-6 py-20">
        <h2 className="text-center text-3xl font-bold text-white">Everything between idea and production</h2>
        <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
          {features.map(f => (
            <div key={f.title} className="card transition hover:border-brand-600">
              <div className="text-3xl">{f.icon}</div>
              <h3 className="mt-4 font-semibold text-white">{f.title}</h3>
              <p className="mt-2 text-sm leading-relaxed text-slate-400">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section id="how" className="border-y border-slate-800/60 bg-slate-900/30">
        <div className="mx-auto max-w-5xl px-6 py-20">
          <h2 className="text-center text-3xl font-bold text-white">How it works</h2>
          <div className="mt-12 grid gap-8 md:grid-cols-3">
            {[
              ['1 · Describe', '"Build me a modern restaurant website with online booking." That is the whole spec.'],
              ['2 · Agent builds', 'The Olze agent scaffolds files, writes components, wires Supabase, runs the build, fixes errors.'],
              ['3 · Ship it', 'Preview live, push to GitHub, deploy to Vercel. Export everything — it is your code.'],
            ].map(([t, d]) => (
              <div key={t}>
                <h3 className="font-semibold text-brand-400">{t}</h3>
                <p className="mt-2 text-sm text-slate-400">{d}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="mx-auto max-w-3xl px-6 py-20">
        <h2 className="text-center text-3xl font-bold text-white">FAQ</h2>
        <div className="mt-10 space-y-4">
          {faqs.map(([q, a]) => (
            <details key={q} className="card group">
              <summary className="cursor-pointer font-medium text-white">{q}</summary>
              <p className="mt-3 text-sm leading-relaxed text-slate-400">{a}</p>
            </details>
          ))}
        </div>
      </section>

      {/* CTA + Footer */}
      <section className="mx-auto max-w-4xl px-6 pb-24 text-center">
        <div className="card border-brand-800 bg-gradient-to-br from-brand-950/40 to-slate-900 p-12">
          <h2 className="text-3xl font-bold text-white">Start building in seconds.</h2>
          <p className="mt-3 text-slate-400">Free forever tier. Real code. Your project, your repo.</p>
          <Link href="/signup" className="btn-primary mt-8">Start Building Free →</Link>
        </div>
      </section>
      <footer className="border-t border-slate-800/60 py-10 text-center text-sm text-slate-500">
        <img src="/olze-logo.svg" alt="Olze" className="mx-auto mb-3 h-6 opacity-70" />
        Olze — free-first AI development platform · Open source core · © 2026
      </footer>
    </main>
  );
}
